### ISSUE TITLE
date of birth should be less than date.now

### ISSUE THREAD

**Issue by GettyOrawo** [Podiihq/nailinda#127]

**Comment by sandeshsoni** [comment]
@GettyOrawo can I help with this issue? I will open a PR

**Comment by GettyOrawo** [comment]
Hey @sandeshsoni Yes sure. Thanks! We love open source contributors. Just create a PR using the template provided and work on it! :slightly_smiling_face:

**Comment by sandeshsoni** [comment]
hey @GettyOrawo I am close to fixing this issue and open a PR.
https://github.com/sandeshsoni/nailinda/commit/7b8c9fbc4948a7e4f36fb95403d7a92d028aeeff

~The problem right now is, if we provide nil DateOfBirth, it still tries to validate if its future date and throws error. Debugging. Ideally it should not.~
